version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"

  seq:
    image: datalust/seq
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
      - "4317:4317"

  gateway:
    build: ./src/ApiGateway
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

  productservice:
    build: ./src/Services/ProductService
    depends_on:
      - kafka
      - sqlserver
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

  cartservice:
    build: ./src/Services/CartService
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

  inventoryservice:
    build: ./src/Services/InventoryService
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

  paymentservice:
    build: ./src/Services/PaymentService
    ports:
      - "5004:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

  orderservice:
    build: ./src/Services/OrderService
    ports:
      - "5005:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
